import { NextRequest, NextResponse } from "next/server";
import { checkAndSyncUser } from "@/lib/user";
import { prisma } from "@/lib/prisma";

export async function POST(req: NextRequest) {
  try {
    const dbUser = await checkAndSyncUser();
    if (!dbUser) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { noteId, message, noteText, history } = await req.json();

    if (!noteId || !message) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    // Verify user owns the note
    const note = await prisma.note.findUnique({
      where: { id: noteId },
      include: { chapter: { include: { subject: true } } },
    });

    if (!note || note.chapter.subject.ownerId !== dbUser.id) {
      return NextResponse.json({ error: "Unauthorized access to note" }, { status: 403 });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "Gemini API key is not configured. Please set GEMINI_API_KEY in environment." },
        { status: 500 }
      );
    }

    // Map history to Gemini's format: roles must be "user" or "model"
    const mappedContents = (history || []).map((msg: any) => {
      return {
        role: msg.sender === "user" ? "user" : "model",
        parts: [{ text: msg.text }],
      };
    });

    // Add current user message
    mappedContents.push({
      role: "user",
      parts: [{ text: message }],
    });

    // System instruction for context
    const systemPrompt = `You are a helpful AI assistant integrated inside Inkwell, a premium note-taking app. 
You assist the user in writing, proofreading, summarizing, formatting, explaining, or expanding their notes.
Try to keep your responses concise, helpful, and beautifully formatted in markdown.

Here is the context of the note they are working on:
- Note Title: "${note.title}"
- Current Note Content Text:
"""
${noteText || ""}
"""`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: mappedContents,
          systemInstruction: {
            parts: [{ text: systemPrompt }],
          },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Gemini API error:", errorText);
      return NextResponse.json({ error: "Error communicating with Gemini API" }, { status: response.status });
    }

    const data = await response.json();
    const modelText = data.candidates?.[0]?.content?.parts?.[0]?.text || "No response generated by AI.";

    return NextResponse.json({ text: modelText });
  } catch (error: any) {
    console.error("Chat API error:", error);
    return NextResponse.json({ error: error.message || "Internal Server Error" }, { status: 500 });
  }
}
