import { NextRequest, NextResponse } from "next/server";
import { checkAndSyncUser } from "@/lib/user";
import { prisma } from "@/lib/prisma";
import { rateLimit } from "@/lib/rate-limit";

export async function POST(req: NextRequest) {
  try {
    // Rate Limit (limit: 10 requests per minute)
    const limitRes = rateLimit(req, { limit: 10, windowMs: 60 * 1000 });
    if (!limitRes.success) {
      return NextResponse.json(
        { error: "Too many requests. Please try again later." },
        {
          status: 429,
          headers: {
            "X-RateLimit-Limit": limitRes.limit.toString(),
            "X-RateLimit-Remaining": limitRes.remaining.toString(),
            "X-RateLimit-Reset": limitRes.resetTime.toString(),
          },
        }
      );
    }

    const dbUser = await checkAndSyncUser();
    if (!dbUser) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { noteId, message, noteText, history, customApiKey } = await req.json();

    if (!noteId || !message) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    if (message.length > 5000) {
      return NextResponse.json({ error: "Message too long (max 5000 characters)" }, { status: 400 });
    }

    if (noteText && noteText.length > 500000) {
      return NextResponse.json({ error: "Note content too long for AI analysis (max 500000 characters)" }, { status: 400 });
    }

    if (history && history.length > 100) {
      return NextResponse.json({ error: "Chat history too long (max 100 messages)" }, { status: 400 });
    }

    // Verify user owns the note
    const note = await prisma.note.findUnique({
      where: { id: noteId },
      include: { chapter: { include: { subject: true } } },
    });

    if (!note) {
      return NextResponse.json({ error: "Note not found" }, { status: 404 });
    }

    const isOwner = note.chapter.subject.ownerId === dbUser.id;

    if (!isOwner) {
      return NextResponse.json({ error: "Unauthorized access to note" }, { status: 403 });
    }

    // Get API Key from request body or fallback to environment variables
    const apiKey = (customApiKey || process.env.GEMINI_API_KEY || "").trim();

    if (!apiKey) {
      return NextResponse.json(
        { error: "Gemini API Key is not configured. Please configure your API key in settings or set GEMINI_API_KEY in your .env file." },
        { status: 400 }
      );
    }

    // Map history to Gemini's format: roles must be "user" or "model"
    const mappedContents = (history || []).map((msg: any) => {
      return {
        role: msg.sender === "user" ? "user" : "model",
        parts: [{ text: msg.text }],
      };
    });

    // Add current user message
    mappedContents.push({
      role: "user",
      parts: [{ text: message }],
    });

    // System instruction for context
    const systemPrompt = `You are a helpful AI assistant integrated inside Scribt, a premium note-taking app. 
You assist the user in writing, proofreading, summarizing, formatting, explaining, or expanding their notes.
Try to keep your responses concise, helpful, and beautifully formatted in markdown.

Here is the context of the note they are working on:
- Note Title: "${note.title}"
- Current Note Content Text:
"""
${noteText || ""}
"""`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: mappedContents,
          systemInstruction: {
            parts: [{ text: systemPrompt }],
          },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Gemini API error:", errorText);
      return NextResponse.json({ error: "Error communicating with Gemini API" }, { status: response.status });
    }

    const data = await response.json();
    const modelText = data.candidates?.[0]?.content?.parts?.[0]?.text || "No response generated by AI.";

    return NextResponse.json({ text: modelText });
  } catch (error: any) {
    console.error("Chat API error:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
